### ISSUE TITLE
Migrate to Talos Roadmap

### ISSUE THREAD

**Issue by budimanjojo** [budimanjojo/home-cluster#831]
These are the list of things I want to do with this migration:

- [x] Use `cilium` instead of `calico` and get rid of `metallb`
- [x] Use BGP to expose LoadBalancer services with `cilium`
- [x] Loadbalancer services will get IP address changes (IP range to CIDR)
- [x] Will be using talos managed `VIP` instead of exernal LB for apiserver endpoint
- [x] `kured` is no longer needed
- [x] `flux` will be suspended during migration and the `old` cluster will be in a 2 nodes cluster while the migration is happening

**Comment by budimanjojo** [comment]
https://github.com/budimanjojo/home-cluster/commit/6347b278fee1110342417d5a8fbaf755cea4ce48

**Comment by budimanjojo** [comment]
https://github.com/budimanjojo/home-cluster/commit/01f37ecf989fd03cb691f18108d0d9345fa8ce84

**Comment by budimanjojo** [comment]
https://github.com/budimanjojo/home-cluster/commit/be5e9a31f79ea4249b68d6a4b337b50488ee8272

**Comment by budimanjojo** [comment]
https://github.com/budimanjojo/home-cluster/commit/7c47d4d1aa3d30a37d63d8e60863f6705c8dd42e

**Comment by budimanjojo** [comment]
Done!
